version: '3'
services:
  apache_pizzaria:
    build: ./site/
    depends_on:
      - mysql_pizzaria
    volumes:
      - ./site/php.ini:/usr/local/etc/php/php.ini
      - ../_data/logs/:/var/log/
      - ../gerenciador/httpdocs/:/var/www/pizzaria/gerenciador/httpdocs/
      - ../gerenciador/app/:/var/www/pizzaria/gerenciador/app/
      - ../gerenciador/cgi-bin/:/var/www/pizzaria/gerenciador/cgi-bin/
      - ../_data/upload/:/var/www/pizzaria/gerenciador/httpdocs/furniture/upload/
    ports:
      - "80:80"
    networks:
      net_pizzaria:
        ipv4_address: 172.29.0.3
  # Data Layer
  mysql_pizzaria:
    image: mysql:5.6.35
    container_name: mysql_pizzaria
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mysql_pizzaria
      - MYSQL_USER=user_pizzaria
      - MYSQL_PASSWORD=123456
    volumes:
      - ../_data/mysql-data/:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      net_pizzaria:
        ipv4_address: 172.29.0.2
networks:
  net_pizzaria:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16